#!/bin/bash

SERVICES="rsyslog postgresql spawn-fcgi nginx \
          rabbitmq-server xivo-sysconfd \
          xivo-provd asterisk \
          ntp munin-node consul xivo-confd"

# Func
function init_data {
    if su - postgres -c "psql -l | grep asterisk" 2>&1 > /dev/null
    then
        return
    fi
    echo "Importing XiVO data ..."
    chmod 755 /tmp/asterisk.sql
    su - postgres -c "psql template1 < /tmp/asterisk.sql"
    xivo-init-db --drop --init
}

function start {
    for service in $SERVICES
    do
        echo "Launch $service ..."
        service $service start
    done
}

function fix_asterisk_init {
    sed -i -e 's/MAXFILES=8192/MAXFILES=/g' /etc/init.d/asterisk
}

function fix_dahdi_init {
    echo -e '#!/bin/sh\n\nexit 0' > /etc/init.d/dahdi
}

function main_loop {
    while true
    do
        echo "Welcome to XiVO !"
        sleep 5
    done
}

# Main
fix_asterisk_init
fix_dahdi_init
start
init_data

if [ ! -z $1 ]
then
    main_loop
fi
