#!/bin/bash

SERVICES="rsyslog postgresql ssh spawn-fcgi nginx \
          rabbitmq-server xivo-sysconfd xivo-confgend \
          xivo-dxtora xivo-provd xivo-agid asterisk \
          xivo-amid xivo-call-logs xivo-agent \
          xivo-ctid xivo-restapi"

DATADIR="/var/lib/postgresql/9.1/main"

function init {
    echo "Creating Postgres data at $DATADIR"
    chmod 755 /tmp/asterisk.sql
    su - postgres -c "psql template1 < /tmp/asterisk.sql"
    xivo-init-db --drop --init
}

function start {
    for service in $SERVICES
    do
        echo "Launch $service ..."
        service $service start
    done
}

sed -i -e 's/MAXFILES=8192/MAXFILES=/g' /etc/init.d/asterisk
start

if ! su - postgres -c "psql -l | grep asterisk" 2>&1 > /dev/null
then
    init
fi
